# Generated by Django 5.2.8 on 2026-05-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_custome_a08692_idx',
            old_name='transactio_customer_33f0ad_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_device__e36881_idx',
            old_name='transactio_device__00f8c7_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_status_71abbb_idx',
            old_name='transactio_status_f2a852_idx',
        ),
    ]
